"""
Generated by Claude
I'm sorry for lazying out, the animationclip yaml was annoying to get right

Converts a BeatLeader replay file to a Unity AnimationClip .anim YAML.

Usage:
    python json_to_unity_anim.py <input bsor> <output.anim> [options]

Options:
    --name NAME         AnimationClip asset name embedded in the YAML  (default: stem of output filename)
    --min-gap SECONDS   Minimum time gap between kept keyframes          (default: 0.01)
    --sample-rate HZ    m_SampleRate written into the clip               (default: 60)
    --no-loop           Set m_LoopTime to 0                              (default: 1 / looping)
"""

import argparse
import json
import sys
import zlib
import re
from pathlib import Path
from bsor.Bsor import make_bsor

# Unity path-hash helper
def unity_path_hash(path: str) -> int:
    """Return the unsigned 32-bit CRC32 Unity uses for a transform path."""
    crc = zlib.crc32(path.encode("utf-8")) & 0xFFFFFFFF
    return crc


# helpers
def fmt(v: float, digits: int = 4) -> str:
    rounded = round(v, digits)
    if rounded == 0.0:
        return "0"
    # Format without trailing zeros
    text = f"{rounded:.{digits}f}".rstrip("0").rstrip(".")
    return text


def deduplicate(frames: list[dict], min_gap: float, min_value_change: float = 0.0) -> list[dict]:
    if not frames:
        return []

    def get_values(f: dict) -> list[float]:
        vals = []
        for path in ("head", "left_hand", "right_hand"):
            if path not in f:
                continue
            p = f[path]["position"]
            r = f[path]["rotation"]
            vals += [p["x"], p["y"], p["z"], r["x"], r["y"], r["z"], r["w"]]
        return vals

    kept = [frames[0]]
    last_vals = get_values(frames[0])

    for frame in frames[1:]:
        curr_vals = get_values(frame)
        time_ok = (frame["time"] - kept[-1]["time"]) >= min_gap
        value_ok = True
        for i in range(len(curr_vals)):
            if (abs(curr_vals[i] - last_vals[i]) < min_value_change):
                value_ok = False
                
        if time_ok and value_ok if value_ok != 0 else time_ok:
            kept.append(frame)
            last_vals = curr_vals

    return kept


# Single-axis curve block
KEYFRAME_SCALAR_TEMPLATE = """\
      - serializedVersion: 3
        time: {time}
        value: {value}
        inSlope: 0
        outSlope: 0
        tangentMode: 136
        weightedMode: 0
        inWeight: 0.33333334
        outWeight: 0.33333334"""
KEYFRAME_ROTATION_TEMPLATE = """\
      - serializedVersion: 3
        time: {time}
        value: {value}
        inSlope: 0
        outSlope: 0
        tangentMode: 0
        weightedMode: 0
        inWeight: 0.33333334
        outWeight: 0.33333334"""
CURVE_BLOCK_TEMPLATE = """\
  - curve:
      serializedVersion: 2
      m_Curve:
{keyframes}
      m_PreInfinity: 2
      m_PostInfinity: 2
      m_RotationOrder: 4
    attribute: {attribute}
    path: {path}
    classID: 4
    script: {{fileID: 0}}"""

def build_editor_curve(frames: list[dict], path: str, attribute: str,
                       value_fn, is_rotation: bool = False) -> str:
    values = [value_fn(f) for f in frames]
    times  = [f["time"] for f in frames]

    if is_rotation:
        # Set all slopes to 0
        slopes = [0.0 for _ in range(len(frames))]
        kf_lines = "\n".join(
            KEYFRAME_ROTATION_TEMPLATE.format(
                time=fmt(f["time"], 5),
                value=fmt(values[i]),
                in_slope=fmt(slopes[i]) if i > 0 else "0",
                out_slope=fmt(slopes[i]) if i < len(frames) - 1 else "0",
            )
            for i, f in enumerate(frames)
        )
    else:
        kf_lines = "\n".join(
            KEYFRAME_SCALAR_TEMPLATE.format(time=fmt(f["time"], 5), value=fmt(values[i]))
            for i, f in enumerate(frames)
        )
    return CURVE_BLOCK_TEMPLATE.format(keyframes=kf_lines, attribute=attribute, path=path)


# Position vector curve
POSITION_KEYFRAME_TEMPLATE = """\
      - serializedVersion: 3
        time: {time}
        value: {{x: {x}, y: {y}, z: {z}}}
        inSlope: {{x: 0, y: 0, z: 0}}
        outSlope: {{x: 0, y: 0, z: 0}}
        tangentMode: 0
        weightedMode: 0
        inWeight: {{x: 0.33333334, y: 0.33333334, z: 0.33333334}}
        outWeight: {{x: 0.33333334, y: 0.33333334, z: 0.33333334}}"""

VECTOR_CURVE_TEMPLATE = """\
  - curve:
      serializedVersion: 2
      m_Curve:
{keyframes}
      m_PreInfinity: 2
      m_PostInfinity: 2
      m_RotationOrder: 4
    path: {path}"""


def build_vector_curve(frames: list[dict], path: str, vec_fn) -> str:
    kf_lines = []
    for f in frames:
        x, y, z = vec_fn(f)
        kf_lines.append(
            POSITION_KEYFRAME_TEMPLATE.format(
                time=fmt(f["time"], 5),
                x=fmt(x), y=fmt(y), z=fmt(z),
            )
        )
    return VECTOR_CURVE_TEMPLATE.format(keyframes="\n".join(kf_lines), path=path)


# Quaternion rotation curve
QUAT_KEYFRAME_TEMPLATE = """\
      - serializedVersion: 3
        time: {time}
        value: {{x: {x}, y: {y}, z: {z}, w: {w}}}
        inSlope: {{x: 0, y: 0, z: 0, w: 0}}
        outSlope: {{x: 0, y: 0, z: 0, w: 0}}
        tangentMode: 0
        weightedMode: 0
        inWeight: {{x: 0.33333334, y: 0.33333334, z: 0.33333334, w: 0.33333334}}
        outWeight: {{x: 0.33333334, y: 0.33333334, z: 0.33333334, w: 0.33333334}}"""

QUAT_CURVE_TEMPLATE = """\
  - curve:
      serializedVersion: 2
      m_Curve:
{keyframes}
      m_PreInfinity: 2
      m_PostInfinity: 2
      m_RotationOrder: 4
    path: {path}"""


def build_rotation_curve(frames: list[dict], path: str, quat_fn) -> str:
    quats = [quat_fn(f) for f in frames]   # list of (x, y, z, w)
    times = [f["time"] for f in frames]
    n = len(frames)

    kf_lines = []
    for i, f in enumerate(frames):
        x, y, z, w = quats[i]
        kf_lines.append(
            QUAT_KEYFRAME_TEMPLATE.format(
                time=fmt(f["time"], 5),
                x=fmt(x), y=fmt(y), z=fmt(z), w=fmt(w),
            )
        )
    return QUAT_CURVE_TEMPLATE.format(keyframes="\n".join(kf_lines), path=path)


BINDING_TEMPLATE = """\
    - serializedVersion: 2
      path: {path_hash}
      attribute: {attribute}
      script: {{fileID: 0}}
      typeID: 4
      customType: {custom_type}
      isPPtrCurve: 0"""


def build_bindings(paths: list[str]) -> str:
    # attribute 1 = m_LocalPosition  (customType 0)
    # attribute 2 = m_LocalRotation quaternion (customType 0)
    lines = []
    for path in paths:
        h = unity_path_hash(path)
        lines.append(BINDING_TEMPLATE.format(
            path_hash=h, attribute=2, custom_type=0))
    for path in paths:
        h = unity_path_hash(path)
        lines.append(BINDING_TEMPLATE.format(
            path_hash=h, attribute=1, custom_type=0))
    return "\n".join(lines)


YAML_TEMPLATE = """\
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!74 &7400000
AnimationClip:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {{fileID: 0}}
  m_PrefabInstance: {{fileID: 0}}
  m_PrefabAsset: {{fileID: 0}}
  m_Name: {clip_name}
  serializedVersion: 6
  m_Legacy: 0
  m_Compressed: 0
  m_UseHighQualityCurve: 1
  m_RotationCurves:
{rotation_curves}
  m_CompressedRotationCurves: []
  m_EulerCurves: []
  m_PositionCurves:
{position_curves}
  m_ScaleCurves: []
  m_FloatCurves: []
  m_PPtrCurves: []
  m_SampleRate: {sample_rate}
  m_WrapMode: 0
  m_Bounds:
    m_Center: {{x: 0, y: 0, z: 0}}
    m_Extent: {{x: 0, y: 0, z: 0}}
  m_ClipBindingConstant:
    genericBindings:
{bindings}
    pptrCurveMapping: []
  m_AnimationClipSettings:
    serializedVersion: 2
    m_AdditiveReferencePoseClip: {{fileID: 0}}
    m_AdditiveReferencePoseTime: 0
    m_StartTime: 0
    m_StopTime: {stop_time}
    m_OrientationOffsetY: 0
    m_Level: 0
    m_CycleOffset: 0
    m_HasAdditiveReferencePose: 0
    m_LoopTime: {loop_time}
    m_LoopBlend: 0
    m_LoopBlendOrientation: 0
    m_LoopBlendPositionY: 0
    m_LoopBlendPositionXZ: 0
    m_KeepOriginalOrientation: 0
    m_KeepOriginalPositionY: 1
    m_KeepOriginalPositionXZ: 0
    m_HeightFromFeet: 0
    m_Mirror: 0
  m_EditorCurves:
{editor_curves}
  m_EulerEditorCurves: []
  m_HasGenericRootTransform: 0
  m_HasMotionFloatCurves: 0
  m_Events: []
"""

def convert(input_path: str, output_path: str, clip_name: str,
            min_gap: float, min_value_change: float, sample_rate: int, loop: bool) -> None:
    raw = bsor2json(input_path)

    raw = re.sub(r",\s*,", ",", raw)

    frames_raw: list[dict] = json.loads(raw)
    print(f"  Loaded {len(frames_raw)} raw keyframes")

    frames = deduplicate(frames_raw, min_gap, min_value_change=min_value_change)
    print(f"  {len(frames)} keyframes kept after deduplication (min_gap={min_gap}s)")

    if not frames:
        print("ERROR: no keyframes remain after deduplication.", file=sys.stderr)
        sys.exit(1)

    stop_time = fmt(frames[-1]["time"], 5)

    paths = ["head", "left_hand", "right_hand"]
    paths = [p for p in paths if p in frames[0]]

    # --- Rotation curves (quaternion, m_RotationCurves) ----------------------
    rot_curve_blocks = []
    for path in paths:
        def quat_xyzw(f, _path=path):
            r = f[_path]["rotation"]
            return r["x"], r["y"], r["z"], r["w"]  # Return as a tuple

        rot_curve_blocks.append(build_rotation_curve(frames, path, quat_xyzw))
    rotation_curves_str = "\n".join(rot_curve_blocks)

    # --- Position curves (m_PositionCurves) ----------------------------------
    pos_curve_blocks = []
    for path in paths:
        def pos_xyz(f, _path=path):
            p = f[_path]["position"]
            return p["x"], p["y"], p["z"]  # Return as a tuple

        pos_curve_blocks.append(build_vector_curve(frames, path, pos_xyz))
    position_curves_str = "\n".join(pos_curve_blocks)

    # --- Editor curves (one per channel) ------------------------------------
    editor_curve_blocks = []
    pos_axes = [
        ("m_LocalPosition.x", lambda f, p: f[p]["position"]["x"]),
        ("m_LocalPosition.y", lambda f, p: f[p]["position"]["y"]),
        ("m_LocalPosition.z", lambda f, p: f[p]["position"]["z"]),
    ]
    rot_axes = [
        ("m_LocalRotation.x", lambda f, p: f[p]["rotation"]["x"]),
        ("m_LocalRotation.y", lambda f, p: f[p]["rotation"]["y"]),
        ("m_LocalRotation.z", lambda f, p: f[p]["rotation"]["z"]),
        ("m_LocalRotation.w", lambda f, p: f[p]["rotation"]["w"]),
    ]
    for path in paths:
        for attr, fn in pos_axes:
            editor_curve_blocks.append(
                build_editor_curve(
                    frames, path, attr,
                    lambda f, _fn=fn, _path=path: _fn(f, _path),
                    is_rotation=False,
                )
            )
    for path in paths:
        for attr, fn in rot_axes:
            editor_curve_blocks.append(
                build_editor_curve(
                    frames, path, attr,
                    lambda f, _fn=fn, _path=path: _fn(f, _path),
                    is_rotation=True,
                )
            )
    editor_curves_str = "\n".join(editor_curve_blocks)

    bindings_str = build_bindings(paths)

    yaml_text = YAML_TEMPLATE.format(
        clip_name=clip_name,
        rotation_curves=rotation_curves_str,
        position_curves=position_curves_str,
        bindings=bindings_str,
        stop_time=stop_time,
        loop_time=1 if loop else 0,
        sample_rate=sample_rate,
        editor_curves=editor_curves_str,
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(yaml_text, encoding="utf-8")
    print(f"Written to {output_path}")
    print(f"  Clip name : {clip_name}")
    print(f"  Stop time : {stop_time}s")
    print(f"  Keyframes : {len(frames)}")
    print(f"  Paths     : {paths}")
    

def bsor2json(input_path: str):
    with open(input_path, 'rb') as f:
        print(f)
        m = make_bsor(f)
        data = json.loads(str(m))
        frames = data.get("frames", [])
        return(str(frames).replace("'", '"'))


def main():
    parser = argparse.ArgumentParser(
        description="Converts a BeatLeader replay file to a Unity AnimationClip .anim YAML"
    )
    parser.add_argument("input", help="Path to input .bsor file")
    parser.add_argument("output", help="Path to output .anim file")
    parser.add_argument(
        "--name",
        default=None,
        help="AnimationClip asset name (default: output filename stem)",
    )
    parser.add_argument(
        "--min-gap",
        type=float,
        default=0.01,
        dest="min_gap",
        help="Minimum time gap (seconds) between kept keyframes (default: 0.01)",
    )
    parser.add_argument(
        "--sample-rate",
        type=int,
        default=60,
        dest="sample_rate",
        help="m_SampleRate value written into the clip (default: 60)",
    )
    parser.add_argument(
        "--no-loop",
        action="store_true",
        dest="no_loop",
        help="Set m_LoopTime to 0 (default: looping enabled)",
    )
    parser.add_argument(
        "--min-value-change",
        type=float,
        default=0.005,
        dest="min_value_change",
        help="Min change in any position/rotation value to force-keep a frame (default: 0.005)",
    )

    args = parser.parse_args()

    clip_name = args.name if args.name else Path(args.output).stem
    
    convert(
        input_path=args.input,
        output_path=args.output,
        clip_name=clip_name,
        min_gap=args.min_gap,
        min_value_change=args.min_value_change,
        sample_rate=args.sample_rate,
        loop=not args.no_loop,
    )
    


if __name__ == "__main__":
    main()
